;/*FB_PKG_DELIM*/

__d("CometTahoeRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="25235390319399252"}),null);
__d("FBUnifiedStoriesTrayType",["$InternalEnum"],(function(a,b,c,d,e,f){a=b("$InternalEnum").Mirrored(["AUTOPLAY_NOTIFICATION_TRAY","FEED_PROFILE_TRAY","FEED_TAB_STORIES_SURFACE","FEED_UNITS_PAGINATION","FRIENDLY_FEED_PROFILE_TRAY","FROM_FEED_INLINE_VIEWER_MULTI_BUCKET_TRAY","GENERIC_CHAINING_QUERY_TRAY","GROUPS_STORIES_TRAY","MONTAGE","MONTAGE_WITH_MUTED_BUCKETS","ONE_BY_ONE_AUTOPLAY","PERMALINK","POG_GARDEN","PORTAL_TRAY","PROFILE_VIEWER_EXTENSION","SHOP_TAB_STORY_TRAY","STORIES_WIDGET_TRAY","SUGGESTED_SIMILAR_STORIES_TRAY","SUGGESTED_STORIES","SUGGESTED_STORIES_FOR_HYBRID_TRAY","TOP_CONNECTIONS","TOP_OF_FEED_TRAY","TOP_OF_FEED_TRAY_SHUFFLE","TOP_OF_FRIENDLY_FEED_TRAY","VIEWER_RANKED_TRAY","WEARABLE_STORIES_FACE_TRAY"]);c=a;f["default"]=c}),66);
__d("FBUnifiedStoriesTrayTypeUtils.facebook",["$InternalEnumUtils","FBUnifiedStoriesTrayType"],(function(a,b,c,d,e,f,g){a=d("$InternalEnumUtils").createToJSEnum(c("FBUnifiedStoriesTrayType"));b=d("$InternalEnumUtils").createFromJSEnum(c("FBUnifiedStoriesTrayType"));g.toJSEnum=a;g.fromJSEnum=b}),98);
__d("StoriesGatingEntrypoint.entrypointutils",["WebPixelRatio","qex"],(function(a,b,c,d,e,f,g){"use strict";function a(a){var b;b=(b=c("qex")._("564"))!=null?b:!1;return{blur:d("WebPixelRatio").get()*10,bucketID:a||"",feedbackSource:65,feedLocation:"COMET_MEDIA_VIEWER",focusCommentID:null,initialBucketID:a||"",initialLoad:!0,isFbNotesIncluded:(a=c("qex")._("4610"))!=null?a:!1,isStoriesArchive:!1,scale:d("WebPixelRatio").get(),shouldDeferLoad:!1,shouldEnableArmadilloStoryReply:b,shouldEnableLiveInStories:!0}}g.getContentPaneParams=a}),98);
__d("StoriesLWRVariant.relayprovider",["qex"],(function(a,b,c,d,e,f,g){"use strict";a={get:function(){return c("qex")._("1276")===!0?"www_new_reactions":"www"}};g["default"]=a}),98);
__d("StoriesSuspenseContentPaneRootWithEntryPointQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="25042378432117976"}),null);
__d("StoriesSuspenseContentPaneRootWithEntryPointQuery$Parameters",["CometUFICommentAvatarStickerAnimatedImage.relayprovider","IsWorkUser.relayprovider","StoriesLWRVariant.relayprovider","StoriesShouldIncludeFbNotes.relayprovider","StoriesSuspenseContentPaneRootWithEntryPointQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("StoriesSuspenseContentPaneRootWithEntryPointQuery_facebookRelayOperation"),metadata:{},name:"StoriesSuspenseContentPaneRootWithEntryPointQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__StoriesShouldIncludeFbNotesrelayprovider:b("StoriesShouldIncludeFbNotes.relayprovider"),__relay_internal__pv__CometUFICommentAvatarStickerAnimatedImagerelayprovider:b("CometUFICommentAvatarStickerAnimatedImage.relayprovider"),__relay_internal__pv__IsWorkUserrelayprovider:b("IsWorkUser.relayprovider"),__relay_internal__pv__StoriesLWRVariantrelayprovider:b("StoriesLWRVariant.relayprovider")}}};e.exports=a}),null);
__d("StoriesSuspenseNavigationPaneRootWithEntryPointQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="25805746322346586"}),null);
__d("StoriesSuspenseNavigationPaneRootWithEntryPointQuery$Parameters",["StoriesSuspenseNavigationPaneRootWithEntryPointQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("StoriesSuspenseNavigationPaneRootWithEntryPointQuery_facebookRelayOperation"),metadata:{},name:"StoriesSuspenseNavigationPaneRootWithEntryPointQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("StoriesCometSuspenseRoot.entrypoint",["FBUnifiedStoriesTrayTypeUtils.facebook","JSResourceForInteraction","StoriesGatingEntrypoint.entrypointutils","StoriesSuspenseContentPaneRootWithEntryPointQuery$Parameters","StoriesSuspenseNavigationPaneRootWithEntryPointQuery$Parameters","WebPixelRatio","qex"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){var e=a.passthroughProps,f=a.routeParams;a=a.routeProps;var g=f.bucket_id,h=a.bucket_id_from_card_id;a=a.buckets_count;f=(f==null?void 0:f.source)==="story_tray";e=d("FBUnifiedStoriesTrayTypeUtils.facebook").fromJSEnum((e=e==null?void 0:e.storiesTrayType)!=null?e:"TOP_OF_FEED_TRAY");f={bucketsCount:a!=null?a:9,extendedViewerInitialBucketID:g!=null?g:"",includeInitialBucket:g!==""&&g!==null&&!f,isFbNotesIncluded:(a=c("qex")._("4610"))!=null?a:!1,pinnedIDs:[g!=null?g:""],scale:d("WebPixelRatio").get(),storiesTrayType:e};a=d("StoriesGatingEntrypoint.entrypointutils").getContentPaneParams(g!=null?g:h);return{queries:{storiesSuspenseContentPaneRootReference:{parameters:b("StoriesSuspenseContentPaneRootWithEntryPointQuery$Parameters"),variables:a},storiesSuspenseNavigationPaneRootReference:{parameters:b("StoriesSuspenseNavigationPaneRootWithEntryPointQuery$Parameters"),variables:f}}}},root:c("JSResourceForInteraction")("StoriesCometSuspenseRoot.react").__setRef("StoriesCometSuspenseRoot.entrypoint")};g["default"]=a}),98);