;/*FB_PKG_DELIM*/

__d("CometContentNotAvailable.react",["fbt","CometContentArea.react","FDSButton.react","FDSNullState.react","NullStateGeneral","XCometHomeControllerRouteBuilder","gkx","react","react-compiler-runtime"],(function(a,b,c,d,e,f,g,h){"use strict";var i,j=i||d("react");function a(a){var b=d("react-compiler-runtime").c(7);a=a.enableBackToFeed;a=a===void 0?!1:a;var e;b[0]===Symbol["for"]("react.memo_cache_sentinel")?(e=c("XCometHomeControllerRouteBuilder").buildURL({}),b[0]=e):e=b[0];e=e;var f;b[1]===Symbol["for"]("react.memo_cache_sentinel")?(f={className:"x6s0dn4 x78zum5 xtp0wl1 xl56j7k xh8yej3"},b[1]=f):f=b[1];var g;b[2]===Symbol["for"]("react.memo_cache_sentinel")?(g=j.jsx(c("FDSNullState.react"),{headline:h._(/*BTDS*/"\u042d\u0442\u043e\u0442 \u043a\u043e\u043d\u0442\u0435\u043d\u0442 \u0441\u0435\u0439\u0447\u0430\u0441 \u043d\u0435\u0434\u043e\u0441\u0442\u0443\u043f\u0435\u043d"),icon:c("NullStateGeneral")}),b[2]=g):g=b[2];b[3]!==a?(e=a&&c("gkx")("8062")&&j.jsx("div",{className:"x6s0dn4 x78zum5 xdt5ytf",children:j.jsx(c("FDSButton.react"),{label:h._(/*BTDS*/"\u041f\u0435\u0440\u0435\u0439\u0442\u0438 \u043a \u041b\u0435\u043d\u0442\u0435 \u043d\u043e\u0432\u043e\u0441\u0442\u0435\u0439"),linkProps:{url:e},padding:"wide",size:"large"})}),b[3]=a,b[4]=e):e=b[4];b[5]!==e?(a=j.jsx("div",babelHelpers["extends"]({},f,{children:j.jsxs(c("CometContentArea.react"),{verticalAlign:"middle",children:[g,e]})})),b[5]=e,b[6]=a):a=b[6];return a}g["default"]=a}),226);
__d("CometFeedStoryDropdownMenuLoggerContext",["react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=a.createContext({nodeID:null});g["default"]=b}),98);
__d("CometMediaViewerRightRailUFIGlimmer.react",["FDSGlimmer.react","react","react-compiler-runtime","react-strict-dom"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||d("react"),j={ufi:{display:"x78zum5",justifyContent:"x1l1ennw",paddingTop:"xyamay9",paddingInlineEnd:"xv54qhq",paddingBottom:"x1l90r2v",paddingInlineStart:"xf7dkkf",$$css:!0},ufiGlimmer:{borderStartStartRadius:"x13t61ll",borderStartEndRadius:"x1kchd1x",borderEndEndRadius:"x1u0fnx4",borderEndStartRadius:"xbxn0j6",height:"x170jfvy",width:"xge0ay3",$$css:!0}};function a(){var a=d("react-compiler-runtime").c(1),b;a[0]===Symbol["for"]("react.memo_cache_sentinel")?(b=i.jsxs(d("react-strict-dom").html.div,{style:j.ufi,children:[i.jsx(c("FDSGlimmer.react"),{index:1,xstyle:j.ufiGlimmer}),i.jsx(c("FDSGlimmer.react"),{index:2,xstyle:j.ufiGlimmer}),i.jsx(c("FDSGlimmer.react"),{index:3,xstyle:j.ufiGlimmer})]}),a[0]=b):b=a[0];return b}g["default"]=a}),98);
__d("FDSChevronLeftFilled12Icon",["cr:14702"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:14702")}),98);
__d("FDSChevronLeftFilled12PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("492482"),12);b=a;g["default"]=b}),98);
__d("FDSChevronRightFilled12Icon",["cr:13981"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:13981")}),98);
__d("FDSChevronRightFilled12PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("492530"),12);b=a;g["default"]=b}),98);
__d("FDSDocumentMagnifyingGlassOutline20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("847136"),20);b=a;g["default"]=b}),98);
__d("FDSEyeCrossFilled20Icon",["cr:14895"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:14895")}),98);
__d("FDSEyeCrossFilled20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("491223"),20);b=a;g["default"]=b}),98);
__d("FDSEyeCrossFilled24PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("511436"),24);b=a;g["default"]=b}),98);
__d("FDSResizeDownFilled20Icon",["cr:14080"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:14080")}),98);
__d("PagesLoggerEventEnum",[],(function(a,b,c,d,e,f){a=Object.freeze({CLICK:"click",CREATE:"create",DELETE:"delete",DRAG:"drag",HOVER:"hover",IMPRESSION:"impression",RECEIVE_REQUEST:"receive_request",RECEIVE_RESPONSE:"receive_response",SAVE:"save",SCROLL:"scroll",SEND_REQUEST:"send_request",SEND_RESPONSE:"send_response",UNSAVE:"unsave",UPDATE:"update"});f["default"]=a}),66);
__d("PagesTypedLogger",["Banzai","GeneratedLoggerUtils","nullthrows"],(function(a,b,c,d,e,f){"use strict";a=function(){function a(){this.$1={}}var c=a.prototype;c.log=function(a){b("GeneratedLoggerUtils").log("logger:PagesLoggerConfig",this.$1,b("Banzai").BASIC,a)};c.logVital=function(a){b("GeneratedLoggerUtils").log("logger:PagesLoggerConfig",this.$1,b("Banzai").VITAL,a)};c.logImmediately=function(a){b("GeneratedLoggerUtils").log("logger:PagesLoggerConfig",this.$1,{signal:!0},a)};c.clear=function(){this.$1={};return this};c.getData=function(){return babelHelpers["extends"]({},this.$1)};c.updateData=function(a){this.$1=babelHelpers["extends"]({},this.$1,a);return this};c.setConnectionClass=function(a){this.$1.connection_class=a;return this};c.setEvent=function(a){this.$1.event=a;return this};c.setEventLocation=function(a){this.$1.event_location=a;return this};c.setEventTarget=function(a){this.$1.event_target=a;return this};c.setLogSource=function(a){this.$1.log_source=a;return this};c.setNavAttributionIDV2Key=function(a){this.$1.nav_attribution_id_v2_key=a;return this};c.setPageID=function(a){this.$1.page_id=a;return this};c.setRawClientTime=function(a){this.$1.raw_client_time=a;return this};c.setSessionid=function(a){this.$1.sessionid=a;return this};c.setTags=function(a){this.$1.tags=b("GeneratedLoggerUtils").serializeVector(a);return this};c.updateExtraData=function(a){a=b("nullthrows")(b("GeneratedLoggerUtils").serializeMap(a));b("GeneratedLoggerUtils").checkExtraDataFieldNames(a,g);this.$1=babelHelpers["extends"]({},this.$1,a);return this};c.addToExtraData=function(a,b){var c={};c[a]=b;return this.updateExtraData(c)};return a}();var g={connection_class:!0,event:!0,event_location:!0,event_target:!0,log_source:!0,nav_attribution_id_v2_key:!0,page_id:!0,raw_client_time:!0,sessionid:!0,tags:!0};f["default"]=a}),66);
__d("PagesLogger",["PagesLoggerEventEnum","PagesTypedLogger"],(function(a,b,c,d,e,f){var g="extra_data_",h={log:function(a,c,d,e,f,h){e===void 0&&(e=null);f===void 0&&(f=[]);var i={},j=h||{};Object.keys(j||{}).forEach(function(a){var b=j[a];(b instanceof Array||b instanceof Object)&&(b=JSON.stringify(b));i[g+a]=b});new(b("PagesTypedLogger"))().setPageID(a).setEvent(c).setEventTarget(d).setEventLocation(e).setLogSource("pages_logger").setTags(f).updateExtraData(i).log()},registerLogOnClick:function(a,c,d,e,f,g){e===void 0&&(e=null),f===void 0&&(f=[]),g===void 0&&(g={}),a.addEventListener("click",function(){h.log(c,b("PagesLoggerEventEnum").CLICK,d,e,f,g)})}};e.exports=h}),null);
__d("addToSet",[],(function(a,b,c,d,e,f){"use strict";function a(a,b){if(a.has(b))return a;a=new Set(a);a.add(b);return a}f["default"]=a}),66);
__d("removeFromSet",[],(function(a,b,c,d,e,f){"use strict";function a(a,b){if(!a.has(b))return a;a=new Set(a);a["delete"](b);return a}f["default"]=a}),66);
__d("useOnRoutableDialogClose",["CometRouteRenderType","react","react-compiler-runtime","useCometRouterDispatcher"],(function(a,b,c,d,e,f,g){"use strict";var h;(h||d("react")).useCallback;function a(a,b){var e=d("react-compiler-runtime").c(8),f=a===void 0?"/":a;e[0]!==b?(a=b===void 0?{}:b,e[0]=b,e[1]=a):a=e[1];var g=a,h=d("CometRouteRenderType").useIsPushView(),i=c("useCometRouterDispatcher")(),j=d("CometRouteRenderType").useIsHosted();e[2]!==g||e[3]!==f||e[4]!==i||e[5]!==j||e[6]!==h?(b=function(){if(i)if(h)return i.popPushView();else if(j)return i.goBack();else return i.go(f,babelHelpers["extends"]({},g,{target:"self"}))},e[2]=g,e[3]=f,e[4]=i,e[5]=j,e[6]=h,e[7]=b):b=e[7];return b}g["default"]=a}),98);