;/*FB_PKG_DELIM*/

__d("CometFeedUnitEditHistoryDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="24932291786407643"}),null);
__d("CometFeedUnitEditHistoryDialogQuery$Parameters",["CometFeedUnitEditHistoryDialogQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometFeedUnitEditHistoryDialogQuery_facebookRelayOperation"),metadata:{},name:"CometFeedUnitEditHistoryDialogQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometFeedUnitEditHistoryDialog.entrypoint",["CometFeedUnitEditHistoryDialogQuery$Parameters","JSResourceForInteraction"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){return{queries:{queryRef:{options:{fetchPolicy:"network-only"},parameters:b("CometFeedUnitEditHistoryDialogQuery$Parameters"),variables:{count:a.count,scale:a.scale,storyID:a.storyID}}}}},root:c("JSResourceForInteraction")("CometFeedUnitEditHistoryDialog.react").__setRef("CometFeedUnitEditHistoryDialog.entrypoint")};g["default"]=a}),98);
__d("FDSEditHistoryFilled20Icon",["cr:14875"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:14875")}),98);
__d("FDSEditHistoryOutline20Icon",["cr:14877"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:14877")}),98);
__d("CometFeedEditHistoryMenuItemCometDialog.react",["fbt","CAAWebClientLoggingEventSource","CometEntryPointDialogTrigger.react","CometFeedUnitEditHistoryDialog.entrypoint","FDSEditHistoryFilled20Icon","FDSEditHistoryOutline20Icon","FDSMenuItem.react","WebPixelRatio","gkx","react","react-compiler-runtime","useCAALoggedOutDialogWrapper","useIsLoggedOut"],(function(a,b,c,d,e,f,g,h){"use strict";var i,j=i||(i=d("react"));i.useCallback;var k=10,l=c("gkx")("20836");function a(a){var b=d("react-compiler-runtime").c(16),e=a.contentToken,f=a.forwardedRef,g=a.onClick;a=a.storyID;var i=c("useIsLoggedOut")(),m;b[0]===Symbol["for"]("react.memo_cache_sentinel")?(m=h._(/*BTDS*/"\u0412\u043e\u0439\u0434\u0438\u0442\u0435 \u043d\u0430 Facebook"),b[0]=m):m=b[0];m=m;b[1]===Symbol["for"]("react.memo_cache_sentinel")?(m={dialogSource:d("CAAWebClientLoggingEventSource").CAAWebClientLoggingDialogSource.FEED,title:m},b[1]=m):m=b[1];var n=c("useCAALoggedOutDialogWrapper")(m);b[2]!==i||b[3]!==n||b[4]!==g?(m=function(a){i?n():(g&&g(),a())},b[2]=i,b[3]=n,b[4]=g,b[5]=m):m=b[5];var o=m;if(e==null||a==null)return null;b[6]===Symbol["for"]("react.memo_cache_sentinel")?(m=d("WebPixelRatio").get(),b[6]=m):m=b[6];e=m;b[7]===Symbol["for"]("react.memo_cache_sentinel")?(m={},b[7]=m):m=b[7];b[8]!==a?(e={count:k,scale:e,storyID:a},b[8]=a,b[9]=e):e=b[9];b[10]!==f||b[11]!==o?(a=function(a){return j.jsx(c("FDSMenuItem.react"),{icon:l?c("FDSEditHistoryOutline20Icon"):c("FDSEditHistoryFilled20Icon"),onClick:function(){return o(a)},primaryText:h._(/*BTDS*/"\u041f\u043e\u0441\u043c\u043e\u0442\u0440\u0435\u0442\u044c \u0438\u0441\u0442\u043e\u0440\u0438\u044e \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u0439"),ref:f,testid:void 0})},b[10]=f,b[11]=o,b[12]=a):a=b[12];b[13]!==e||b[14]!==a?(m=j.jsx(c("CometEntryPointDialogTrigger.react"),{dialogEntryPoint:c("CometFeedUnitEditHistoryDialog.entrypoint"),otherProps:m,preloadParams:e,children:a}),b[13]=e,b[14]=a,b[15]=m):m=b[15];return m}g["default"]=a}),226);
__d("CometFeedEditHistoryMenuItem_storyMenuItem.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"CometFeedEditHistoryMenuItem_storyMenuItem",selections:[{alias:null,args:null,concreteType:"Story",kind:"LinkedField",name:"story",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null}],storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"content_token",storageKey:null}],type:"StoryEditHistoryMenuItem",abstractKey:null};e.exports=a}),null);
__d("CometFeedEditHistoryMenuItem.react",["CometFeedEditHistoryMenuItemCometDialog.react","CometFeedEditHistoryMenuItem_storyMenuItem.graphql","CometRelay","react","react-compiler-runtime"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j=i||d("react");function a(a){var e,f=d("react-compiler-runtime").c(5),g=a.onClick,i=a.ref;a=a.storyMenuItem;a=d("CometRelay").useFragment(h!==void 0?h:h=b("CometFeedEditHistoryMenuItem_storyMenuItem.graphql"),a);e=(e=a.story)==null?void 0:e.id;g=g;a=a==null?void 0:a.content_token;var k;f[0]!==a||f[1]!==g||f[2]!==i||f[3]!==e?(k=j.jsx(c("CometFeedEditHistoryMenuItemCometDialog.react"),{contentToken:a,forwardedRef:i,onClick:g,storyID:e}),f[0]=a,f[1]=g,f[2]=i,f[3]=e,f[4]=k):k=f[4];return k}g["default"]=a}),98);
__d("CometFeedEditHistoryMenuItem_storyMenuItem$normalization.graphql",[],(function(a,b,c,d,e,f){"use strict";a={kind:"SplitOperation",metadata:{},name:"CometFeedEditHistoryMenuItem_storyMenuItem$normalization",selections:[{alias:null,args:null,concreteType:"Story",kind:"LinkedField",name:"story",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null}],storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"content_token",storageKey:null}]};e.exports=a}),null);
__d("FDSEditHistoryFilled20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("486483"),20);b=a;g["default"]=b}),98);
__d("FDSEditHistoryOutline20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("649685"),20);b=a;g["default"]=b}),98);